### ISSUE TITLE
6a esc ph10 #1 of 4 error 255.255

### ISSUE THREAD

**Issue by skottlotz** [blheli-configurator/blheli-configurator#104]
chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1587823/Log.txt)

**Comment by skottlotz** [comment]
closed? i need help!

**Comment by skottlotz** [comment]
So. What's the answer?


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Andrey Mironov <notifications@github.com> Date: 12/26/17  2:06 PM  (GMT-06:00) To: blheli-configurator/blheli-configurator <blheli-configurator@noreply.github.com> Cc: skottlotz <skottlotz@gmail.com>, Author <author@noreply.github.com> Subject: Re: [blheli-configurator/blheli-configurator] 6a esc ph10 #1 of 4
  error 255.255 (#104) 
Closed #104.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/blheli-configurator/blheli-configurator","title":"blheli-configurator/blheli-configurator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/blheli-configurator/blheli-configurator"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #104."}],"action":{"name":"View Issue","url":"https://github.com/blheli-configurator/blheli-configurator/issues/104#event-1401867244"}}}

**Comment by DieHertz** [comment]
This repo for development, not a place to drop your one-liner issue and get immediate help.
Tick the "Ignore inappropriate MCU and Layout" checkbox while flashing, just as the error message suggests you, if it doesn't help - forward your question to RCGroups.
![image](https://user-images.githubusercontent.com/1427681/34411842-816f6a8a-ebea-11e7-8b7f-a8fb003c0358.png)
