### ISSUE TITLE
Racestart 30amp special edition wont read?

### ISSUE THREAD

**Issue by ScottDunk** [blheli-configurator/blheli-configurator#111]
Hi,

I have racestar 30amp special edition and Matek f405 FC, I can connect using GUI but when I click "read setup" the screen stays blank.  have tried unsetting DSHOT so just using multishot but still not actually reading anything.  After clicking read I get a message stating read successful but just a blank screen.

What am I doing wrong?

**Comment by DieHertz** [comment]
You have blheli32

**Comment by ScottDunk** [comment]
Oh yea, what a doughnut.  Thanks now downloaded blhelisuite32 and all is good with the world 👍
