### ISSUE TITLE
having problems

### ISSUE THREAD

**Issue by hlfdead1221** [blheli-configurator/blheli-configurator#117]
im trying to flash my esc's but the 4th one wont show up only the first 3 ???? everything is hooked up properly the motor arms and it flys but the esc does not show up in the configurator to flash.. Please help..

**Comment by richard-scott** [comment]
I would try re-flashing firmware to your Flight Controller as sometimes that can help. Ensure you have the latest standalone BetaFlight Configurator if that is what you are using. Double check you have the correct firmware image you are flashing too. I would also re-solder the signal/ground pads on the Flight Controller to ensure they are good.
