### ISSUE TITLE
not working.

### ISSUE THREAD

**Issue by chriswactor** [blheli-configurator/blheli-configurator#118]
[I'm running bf 32 35a and its not giving me a way to check my esc or change them. 
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1701753/Log.txt)

**Comment by richard-scott** [comment]
BLHeli_32 is not supported right now. You need the other [Suite](https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite).
