### ISSUE TITLE
can't see esc's

### ISSUE THREAD

**Issue by Arctic13** [blheli-configurator/blheli-configurator#119]
typhoon 32 V2 4in1  see esc's once connected to blheli config see debug log. 

esc is typhoon 32 V2 4in1
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1701934/Log.txt)

**Comment by mdmbc** [comment]
Blheli_32 is not currently supported.

**Comment by chawagon03** [comment]
Is there any chance that BLHeli_32 is coming soon? Or not in scope as of now?
