### ISSUE TITLE
Read setup

### ISSUE THREAD

**Issue by Pate64** [blheli-configurator/blheli-configurator#122]
Why ESC visible do not enter after I press "Read Setup".
At up it show following:
2018-02-14 @ 13:49:48 -- Reading setup

2018-02-14 @ 13:49:49 -- Reading setup finished

But screen stay white :(

My ESC is:
40A BL32_40A 3-5S ESC BLHeli_32

Computer Windows 10.

**Comment by DieHertz** [comment]
There's no BLHeli_32 support, get BLHeliSuite_32.
