### ISSUE TITLE
click read set up and nothing happends????

### ISSUE THREAD

**Issue by Cleevm** [blheli-configurator/blheli-configurator#127]
when i plug into blheli it connects just fine but when i click read set up it dosent take me to the main configuration screen help?

**Comment by DieHertz** [comment]
Which ESCs?

**Comment by Cleevm** [comment]
blheli dys 35a

**Comment by DieHertz** [comment]
Could you show a product link?

**Comment by Cleevm** [comment]
[Log help.txt](https://github.com/blheli-configurator/blheli-configurator/files/1749186/Log.help.txt)

**Comment by Cleevm** [comment]
https://www.banggood.com/DYS-BLHeli_32bit-35A-35amp-Brushless-ESC-2-6S-Dshot1200-Ready-For-FPV-Racing-p-1148598.html?gmcCountry=US&currency=USD&createTmp=1&utm_source=googleshopping&utm_medium=cpc_ods&utm_content=heath&utm_campaign=pla-multi-us-pc&gclid=CjwKCAiA8bnUBRA-EiwAc0hZk5vZFu4ZwPiLUfNaZdN0xTRJxrZD9wjUPNOCj30Ooc39FmLj9pYOURoCBG8QAvD_BwE&cur_warehouse=HK

**Comment by DieHertz** [comment]
Your ESC is BLHeli32, BLHeli32 is a closed-source firmware and unfortunately it's not supported

**Comment by Cleevm** [comment]
ok thanks

**Comment by Cleevm** [comment]
is there a configurator that will work with the ecs?
