### ISSUE TITLE
Is there any configurators that will work with BLHeli32 ESCs 

### ISSUE THREAD

**Issue by Cleevm** [blheli-configurator/blheli-configurator#128]

**Comment by Cleevm** [comment]
If blheli dose not support my escs then is there a different configurator that will?

**Comment by richard-scott** [comment]
https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite

**Comment by Cleevm** [comment]
I'm using Mac :(

**Comment by richard-scott** [comment]
Most people seem to run that Suite in a Windows VM on their Mac.

**Comment by V8Darren** [comment]
https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite

This link does not work. Does anyone know of an alternative?
