### ISSUE TITLE
JBardwell F4 AIO spark and smoke

### ISSUE THREAD

**Issue by Cleevm** [blheli-configurator/blheli-configurator#129]
just got and finished building a quad with JBardwell F4 AIO and plugged in to fly after setting up in betaflight even did a test hover and all of the sudden there was a spark followed with smoke it seems like the whole board is fried can anyone explain what just happened

**Comment by ravini-mephisto** [comment]
You shorted your board somehow, which sucks, but why are you filing an issue for this software about it?
