### ISSUE TITLE
Screen freezes when I plug in.

### ISSUE THREAD

**Issue by AstroSeth51** [blheli-configurator/blheli-configurator#132]
My PC screen freezes when I plug (USB cable) my drone into it, it most certainly won't connect, therefore, I'm not able to update the board on it. The Port is /dev/rfcomm0. is that wrong? I'm new to drone racing, but anything helps. My drone is the Eachine Wizard x220s.

**Comment by DieHertz** [comment]
Wrong port, check the port name you use in BF Configurator and use the same

**Comment by AstroSeth51** [comment]
Well I gave her a try, but I'm gonna be completely honest, it came with same results, as last time. What is your port maybe I could give her a try.
