### ISSUE TITLE
ESC not recognized when connected to 4-8 PWM connectors

### ISSUE THREAD

**Issue by Enzzer** [blheli-configurator/blheli-configurator#134]
Hi,
Yesterday after crashing my quad I noticed that the motor connected to the 4th PWM connector wasn't working.
After some playing around I came to the realization that 4-8 PWM connectors don't give any signal to the ESCs.
Using the motors tab in cleanflight allows me to spin motors connected to 1-3 PWMs but I get no response when trying to spin motor #4.

This is what I know:
* ESCs connected to 1-3 PWMs are recognized perfectly in blheli configurator. I also get regular ESC tones (low-mid-high, low-high).
* Connecting ESCs to 4-8 PWMs doesn't get any signal to the connected ESC. Moreover, when connecting to the 4th PWM I get only the first set of tones (low-mid-high) while connecting to 5-8 PWMs gives me no tones at all.

This is what I did:
* Re-soldered the 4th PWM connection pins.
* Verified ESCs+motors are all good by using a servo tester + connecting them to 1-3 PWM which work perfectly. 
* Tried resetting cleanflight settings of my FC to default.

This is what I have:
* F3 Deluxe FC ([https://hobbyking.com/en_us/seriously-pro-racing-f3-fc-board-deluxe-with-internal-osd.html](url))
* Racestar motors + blheli_s ESCs

Any help would be highly appreciated,
Thanks!

**Comment by DieHertz** [comment]
Sounds like a dead motor output.
If there's the first set of tones, that means the line is LOW, and that usually is the case with a dead motor output.
