### ISSUE TITLE
ESC Read Setup not working

### ISSUE THREAD

**Issue by CC268** [blheli-configurator/blheli-configurator#138]
Really frustrating. Running Butterflight on the Bardwell F4 board. Spedix GS30 ESCs. Crossfire Micro RX. Go to Read Setup and it runs and says it is finished, but nothing comes up. I need to reverse the motor direction on two of my motors. How can I get this fixed?

Thanks.

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1822342/Log.txt)

**Comment by DieHertz** [comment]
BLHeli 32 is not supported

**Comment by Hotdogs4** [comment]
What can you use, then? I have the same problem

**Comment by DieHertz** [comment]
Butterflight not supported.
