### ISSUE TITLE
Is it possible to get a standalone installer for BLHeli?

### ISSUE THREAD

**Issue by neilbalch** [blheli-configurator/blheli-configurator#142]
I would really like to use the BLHeli configurator without installing Chrome, like what the CleanFlight Configurator offers through [releases](https://github.com/cleanflight/cleanflight-configurator/releases).

Could this be added to the repository without much fuss?

Thanks,
Neil

**EDIT:**
It appears that a major step in this process might involve the merger of [this pull request](https://github.com/blheli-configurator/blheli-configurator/pull/126#pullrequestreview-111458841). I am not an expert with these kinds of apps, but it appears to me that it is quite possible indeed.

**Comment by DieHertz** [comment]
There already are standalone releases provided from the same times CF/BF started to distribute standalone.
Coincidentally they also are located on the releases page :)

**Comment by neilbalch** [comment]
@DieHertz On the releases page of this repo?

**Comment by neilbalch** [comment]
Ah, I see them. They really should be advertised in the installation section of the README.
