### ISSUE TITLE
Bl Heli not responding after reading setup?

### ISSUE THREAD

**Issue by CptnCrash** [blheli-configurator/blheli-configurator#144]
After connecting and reading setup nothing happens - just left with a blank page. I'm running Dalrc engine 4in1 ESC's with the DAL RC f405 FC. i need to update the firmware and change a motor direction. 

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1901867/Log.txt)

**Comment by DieHertz** [comment]
BLHeli_32 is not supported

**Comment by CptnCrash** [comment]
it say it is on the website.  What would you suggest I do?

**Comment by DieHertz** [comment]
Where does it say so? Could you give a link? :)
Use the windows-only configurator.

**Comment by CptnCrash** [comment]
http://www.dalrcmodel.com/DALRC/plus/view.php?aid=182

**Comment by CptnCrash** [comment]
http://www.blheli32.com/list-of-blheli_32-escs/

**Comment by CptnCrash** [comment]
Thanks
