### ISSUE TITLE
DYS F4 Pro v2 Board with DYS Aria 32 bit ESCs will not read setup

### ISSUE THREAD

**Issue by mrcbr76** [blheli-configurator/blheli-configurator#145]
When I enter into BL Heli configurator and run read setup I get nothing.  Betaflight is open and I have a battery hooked up.  

[BL Heli Config Debug Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1930288/BL.Heli.Config.Debug.Log.txt)

**Comment by DieHertz** [comment]
Unfortunately blheli 32 is not supported
