### ISSUE TITLE
BLHELI won't read the esc's ?

### ISSUE THREAD

**Issue by Flytime1958** [blheli-configurator/blheli-configurator#160]
I'm having a problem that BLheli won't read set up? Incoming port is ok when connecting . Powering it up with the battery ans then the tab read set-up it only says finished and there is nothing on the screen.

**Comment by holoduke** [comment]
same here.

**Comment by bigey** [comment]
Connection is ok but failed to read ESC.
```
Reading setup
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 6,51,104,4
sending cmd_DeviceReadEEprom 0 112
received cmd_DeviceReadEEprom ACK_I_INVALID_CMD 0 0
received cmd_DeviceReadEEprom ACK_I_INVALID_CMD 0 0
ESC 1 read settings failed cmd_DeviceReadEEprom ACK_I_INVALID_CMD
```

[complete debug log here](https://github.com/blheli-configurator/blheli-configurator/files/2386460/Log.txt)

Any ideas ?

**Comment by DieHertz** [comment]
You have blheli 32, and it's not supported. You'll have greater luck using Wine

**Comment by bigey** [comment]
Thank you @DieHertz. I was able to read ESC using BLHELI suite running on Linux with Wine!
