### ISSUE TITLE
BL_heli configurator: Problem with "Read Setup" Button

### ISSUE THREAD

**Issue by jfrinconc** [blheli-configurator/blheli-configurator#163]
Hi, I think I'm having a problem with my quad. I'm able to connect it to BL_heli configurator, but when I click on "Read Setup" button nothing is loaded.

My FC is a Holybro Kakute V2, for ESCs I'm using 4 DYS Aria BLHeli_32bit 35A.

Attached I send the debug log and a screenshot of BL_heli configurator. I'd really appreciate your help.

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/2482681/Log.txt)
 
![screenshot](https://user-images.githubusercontent.com/44197167/47012019-e6fbb800-d108-11e8-8ac1-056787ff670d.png)

**Comment by DzikuVx** [comment]
BLHeli_32 is not supported and will not be since protocol is not open
