### ISSUE TITLE
Sliders do not get focus

### ISSUE THREAD

**Issue by DieHertz** [blheli-configurator/blheli-configurator#26]
Sliders do not get focus from mouse drag and act weirdly overall.

**Comment by LightningStalker** [comment]
This is actually preventing some of the custom startup tones from being accessible in BlHeli-Multishot.

**Comment by DieHertz** [comment]
In v1.0.4 you can now use arrow keys. Will look into the mouse-drag behaviour later.

**Comment by LightningStalker** [comment]
Just noticed this working now thanks

**Comment by DieHertz** [comment]
@LightningStalker yeah, enjoy!
