### ISSUE TITLE
DALRC XR20A ESC timeout

### ISSUE THREAD

**Issue by FPVDrone** [blheli-configurator/blheli-configurator#28]
[Log - Blheli Configurator App.txt](https://github.com/blheli-configurator/blheli-configurator/files/673670/Log.-.Blheli.Configurator.App.txt)

After I clicked readsetup, it sounded finish but did not show the detail.  Attached is the related log.  Please advise.

Thanks!
Andy

**Comment by DieHertz** [comment]
Thanks for reporting, this appears to be a duplicate of #27.

**Comment by DieHertz** [comment]
Please try v1.0.3
