### ISSUE TITLE
Only motor 1 and 2 show up in the config.

### ISSUE THREAD

**Issue by Noslippin** [blheli-configurator/blheli-configurator#37]
[esclog_3motors.txt](https://github.com/blheli-configurator/blheli-configurator/files/692446/esclog_3motors.txt)
[ecslog12-28.txt](https://github.com/blheli-configurator/blheli-configurator/files/692447/ecslog12-28.txt)

**Comment by DieHertz** [comment]
First log shows 3 ESCs read succesfully: 2-3-4.
Second log shows no ESCs read - you probably forgot to connect battery.
In both cases your flight controller indicates that it could not connect to the ESC - check your wiring, make sure your ESC is powered up and not dead.
I can't do anything on the configurator side if `cmd_DeviceInitFlash` indicates GENERAL_ERROR.
