### ISSUE TITLE
Cannot read ESC's

### ISSUE THREAD

**Issue by jorimax** [blheli-configurator/blheli-configurator#45]
Dear support,

I am trying to connect to my Racerstar esc's via the BLheli suite but I keep on getting errors. (I have done this before so I know how it works) The tool finds ESC's in Silabs mode and I have used option E
When I connect the battery I hear the correct tones. Then I select "Read Setup" and a pop-up shows rebooting the FC and I get the error "connection to fc failed check port and power" etc.. 
I can connect fine with Betaflight. I have flashed the latest Spracingf3 Firmware.

2017-02-13 @ 23:45:58 -- Serial port successfully opened with ID: 3
2017-02-13 @ 23:45:58 -- MultiWii API version received - 1.31.0
2017-02-13 @ 23:45:58 -- Flight controller info, identifier: BTFL, version: 3.1.5
2017-02-13 @ 23:45:58 -- Running firmware released on: Feb 7 2017 22:30:44
2017-02-13 @ 23:45:58 -- Board: SRF3, version: 0
2017-02-13 @ 23:45:58 -- Unique device ID received - 0x3e002b5633571520313639
2017-02-14 @ 00:00:39 -- Serial port successfully closed

Could there be something wrong with the FC or USB port?

Thanks a lot!
Jori

![screenshot026](https://cloud.githubusercontent.com/assets/25756188/22907597/2a99ccf4-f24a-11e6-901d-ce5c802439c7.jpg)

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/772641/Log.txt)

**Comment by andymac4182** [comment]
Hi @jorimax,
This repo is for the chrome app. https://chrome.google.com/webstore/detail/blheli-configurator/mejfjggmbnocnfibbibmoogocnjbcjnk

Have you given that a go?

Cheers,
Andrew

**Comment by jorimax** [comment]
yes i have and the same result.
thx a lot
joep

Op 14 feb. 2017 00:34 schreef "Andrew McClenaghan" <notifications@github.com

**Comment by jorimax** [comment]
the log is actually from the chrome app.


Op 14 feb. 2017 00:34 schreef "Andrew McClenaghan" <notifications@github.com
>:

Hi @jorimax <https://github.com/jorimax>,
This repo is for the chrome app. https://chrome.google.com/
webstore/detail/blheli-configurator/mejfjggmbnocnfibbibmoogocnjbcjnk

Have you given that a go?

Cheers,
Andrew

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blheli-configurator/blheli-configurator/issues/45#issuecomment-279558916>,
or mute the thread

**Comment by andymac4182** [comment]
Just confirming you have the ESCs powered up from the battery when you are attempting to connect?

**Comment by DieHertz** [comment]
Looks like something wrong with passthrough or serial connection, I'll check my SPRF3 on BF3.1.5 tomorrow.

**Comment by jorimax** [comment]
yes i do

Op 14 feb. 2017 01:09 schreef "Andrew McClenaghan" <notifications@github.com

**Comment by jorimax** [comment]
thanks a lot!

Op 14 feb. 2017 01:21 schreef "Andrey Mironov" <notifications@github.com>:

**Comment by jorimax** [comment]
Hi Andrew,

Thanks a lot for your time!

I forgot to mention that the quad is actually flying, I managed to configure the ESC's after the build.
One thing I noticed is that one ground wire from a ESC is "almost" touching the outer case of the USB port. Could this be the problem?

The strange thing is that I can connect just fine and use BetaFlight etc... so the USB port should be ok. But when I connect the battery it goes wrong. 

Thanks a lot for your help!

Kr,
Joep

**Comment by jorimax** [comment]
Hi Andrey,

Did you managed to test it?
It seems indeed an issue with the passthrough.
I also noticed that BF stops responding once I connect a battery?

thx,
Joep

2017-02-14 1:21 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by DieHertz** [comment]
Checked SPRF3 on 3.1.5, passthrough and BFC work for me.
Your issue looks very similar to what happens when USB UART is shared with some other function as OSD or SPORT telemetry. Any chance you have something connected to UART1?

**Comment by jorimax** [comment]
UART 1 is USB I disabled this one and as a result I needed to reflash.
I use UART 2 for 5v for a LED strip so this might be the issue???
UART 3 is Serial RX

2017-02-15 21:48 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by DieHertz** [comment]
MSP should be enabled on UART1, and nothing should be connected to it, otherwise it interferes with normal USB operation, that usually happens when you apply power (e.g. connect your battery).

Do you have a logic analyzer? You could hook it up to UART1 and see what happens when you connect the battery.

**Comment by jorimax** [comment]
I have MSP on uart 1 and 2
But I think I have indeed connected either the led or the OSD to uart 1
So I need to move the OSD to uart 2 and do not attach anything to uart 1?

thx!

2017-02-15 21:55 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by DieHertz** [comment]
Yes, precisely! Move the OSD and leave UART1 alone, that should fix your issue.

**Comment by jorimax** [comment]
man this took me hours!
Thanks a lot!
really appreciated!

I let you know if it's fixed!


2017-02-15 22:04 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by jorimax** [comment]
Can I take only 5V from uart1?

2017-02-15 22:04 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by DieHertz** [comment]
Sure, all 5V outputs are equal and internally connected.

**Comment by jorimax** [comment]
Problem solved!
So happy!

Thanks a lot!

2017-02-15 22:13 GMT+01:00 Andrey Mironov <notifications@github.com>:

**Comment by DieHertz** [comment]
Glad you made it.
Apologies for not pin-pointing the cause earlier. I suggest you join BetaFlight Slack Channel via betaflight.nz, there are lots of knowledgeable people and BF devs.

**Comment by jorimax** [comment]
I will thanks again!

2017-02-15 22:42 GMT+01:00 Andrey Mironov <notifications@github.com>:
