### ISSUE TITLE
help please 

### ISSUE THREAD

**Issue by SoundPirate** [blheli-configurator/blheli-configurator#50]
Running - OS: <strong>MacOS</strong>, Chrome: <strong>57.0.2987.133</strong>, Configurator: <strong>1.0.11</strong>
Selecting last used port: /dev/tty.SLAB_USBtoUART
Connecting to: /dev/tty.SLAB_USBtoUART
SERIAL: Connection opened with ID: 3, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 3
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
Unknown code detected: 116
Unknown code detected: 150
Unknown code detected: 110
MSP data request timed-out: 1
MultiWii API version <span style="color: green">received</span> - <strong>1.35.0</strong>
Flight controller info, identifier: <strong>CLFL</strong>, version: <strong>2.0.0</strong>
Running firmware released on: <strong>Apr 13 2017 01:07:51</strong>
Board: <strong>SRF3</strong>, version: <strong>0</strong>
Unique device ID <span style="color: green">received</span> - <strong>0x2b00394234571920363434</strong>

Hi I flashed my ese to 16.6 now only one motor spins and does not read the other 3 
the code above is my debug log from before flash any help would be appreciated 

kind regards

brian
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/945689/Log.txt)

**Comment by HighTechPauper** [comment]
I found that having port peripherals enabled messed up the comm with esc's. Disabled port peripherals (RunCam, SmartAudio, Tramp) and all was well again. So now I just remember to disable the ports mods before I do any esc work
