### ISSUE TITLE
Reads ESCs randomly, can't flash

### ISSUE THREAD

**Issue by StormRU** [blheli-configurator/blheli-configurator#61]
- ESC 4in1 Racerstar RS20x4 V1
- Latest MacOS + Chrome Blheli Configurator 1.0.14 (latest to date)
- Matek F405 FC

Blheli shows 1, 2, sometimes 3 or all 4 esc but ESC2 and ESC3 has corrupted names:
ESC 2: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ, 16_65, ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
ESC 3: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ, 16_65, ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

When I try to reflash it crashes with this an error:
**ESC 2: flashing failed - Error: LAYOUT found ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ #G_L_30# expected**

<img width="719" alt="2017-07-06 11 10 15" src="https://user-images.githubusercontent.com/6052345/27902058-fc3faee2-623c-11e7-888f-474d477d54cc.png">
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1127180/Log.txt)

**Comment by DieHertz** [comment]
Tick the "ignore MCU" checkbox.

**Comment by StormRU** [comment]
it worked! Thanks
