### ISSUE TITLE
Will not flash different FW

### ISSUE THREAD

**Issue by claytonbakerjr** [blheli-configurator/blheli-configurator#63]
Hi I have 4 Little Bee Spring 30amp esc's.
2 of them were loaded with AH20/16.6 the other 2 were loaded with AH25/16.5
After researching it seems the correct version for these esc's is AH25 so
I updated the AH25s to 16.6 and then tried to flash the AH20's to the same but receive an error.
(flashing failed - error: layout found #a_h_20#, #a_h_25# expected at checkescandmcu)
Obviously I am flashing one at a time since the flash all button is greyed out.
Is this as simple as checking the box that states: "Ignore inappropriate MCU and Layout"
and then try again? I want to check with someone before doing so.

**Comment by DieHertz** [comment]
Yes, tick the checkbox. But be mindful of what you're doing.
