### ISSUE TITLE
ESC Flashing Error

### ISSUE THREAD

**Issue by stephenbsn** [blheli-configurator/blheli-configurator#64]
I have DYS XS30A ESCs. 3 of the 4 ESCs flashed just fine, but ESC 1 will not flash and just gives me an error code 255.255. 
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1166108/Log.txt)

**Comment by HighTechPauper** [comment]
I found that having port peripherals enabled messed up the comm with esc's after upgrade and I could no longer read or flash some or all of them. Disabled port peripherals (RunCam, SmartAudio, Tramp) and all was well again. So now I just remember to disable the ports mods before I do any esc work
