### ISSUE TITLE
Wraith 32 with CL racing f4.  BF 3.2 hex

### ISSUE THREAD

**Issue by 0higgins0** [blheli-configurator/blheli-configurator#66]
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1167511/Log.txt)

Configurator connects, but I just have a white screen.

**Comment by DieHertz** [comment]
BLHeli_32 is not supported

**Comment by 0higgins0** [comment]
Ya sorry. Wrong blheli version
