### ISSUE TITLE
3 ESC no detected

### ISSUE THREAD

**Issue by dragonFPV** [blheli-configurator/blheli-configurator#74]
Hello, I was upgrading my esc to a new version of BLheli_s when I 
unintentionally press the ``defaults´´ button, and my 3rd esc said failed to flash, the 2nd and 1st said flashing sucesfully, and 4th ESC said, unknown, So I disconnected and re-connect on bhlehi configurator, and now only appears the 3rd ESC and the other 3 dissapeard and I can´t do anything like reflash them.
![only 3rd esc appears](https://user-images.githubusercontent.com/32023544/30516062-823bd32e-9b34-11e7-96f1-d2c798c9a7e8.png)

**Comment by HighTechPauper** [comment]
I found that having port peripherals enabled messed up the comm with esc's. Disabled port peripherals (RunCam, SmartAudio, Tramp) and all was well again. So now I just remember to disable the ports mods before I do any esc work
