### ISSUE TITLE
Connection works but "Read setup" doesn't show anything.

### ISSUE THREAD

**Issue by vinz486** [blheli-configurator/blheli-configurator#78]
Hi,
using this machine http://www.overskyrc.com/warlark-pro-brushless-fpv-whoop-drone-racing-quad-copter-p-776.html
I cannot read ESC configuration: when I click on "read setup" the log shows as "read finished" but nothing happens on configuration window.

Betafligth is 3.2.0. RC5

Log is attached to this post.

Thank you!

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1326584/BLHELY_conf_with_BF3.2.0RC5.txt)

**Comment by jplong74** [comment]
this is what i get as well

**Comment by DieHertz** [comment]
Have you powered your ESCs first?

**Comment by jplong74** [comment]
I did yes

**Comment by vinz486** [comment]
Yes, I tried both with battery and without.

**Comment by DieHertz** [comment]
I have the same quad now and don't experience this issue :-(
I may only recommend reflashing ESCs from scratch in BLHeliSuite, usually after that the issue never manifests itself

**Comment by HighTechPauper** [comment]
I found that having port peripherals enabled messed up the comm with esc's.  Disabled port peripherals (RunCam, SmartAudio, Tramp) and all was well again.  So now I just remember to disable the ports mods before I do any esc work

**Comment by mchaos** [comment]
I am having this issue, and I have disable everything and it still does not work.

**Comment by TrueExile** [comment]
I am also having the same issues it seems. 

I have a fresh copy of blheli and am using a emax magnum v2 
Have tried with both peripherals on and off. battery is of coarse plugged in when reading

**Comment by mchaos** [comment]
I figured out my issue. I am new to blheli32, and did not realize that the BLHeli configurator does not work with BLheli32. You have to use BLheli32 suite... I am a linux man, so had to do some special stuff to get it to connect in wine, but works good... More options
