### ISSUE TITLE
Gets stuck on "Waiting for data"

### ISSUE THREAD

**Issue by sean-duffy** [blheli-configurator/blheli-configurator#8]
Tried this on OS X El Capitan 10.11.5 with Favourite BLHeli_S ESCs and it gets stuck on the "Waiting for data" screen. Here is the output of the log:

2016-10-11 @ 13:59:35 -- Running - OS: MacOS, Chrome: 53.0.2785.143, Configurator: 0.0.8
2016-10-11 @ 13:59:48 -- Serial port successfully opened with ID: 3
2016-10-11 @ 13:59:48 -- MultiWii API version received - 1.20.0
2016-10-11 @ 13:59:48 -- Flight controller info, identifier: BTFL, version: 3.0.0
2016-10-11 @ 13:59:48 -- Running firmware released on: Sep 11 2016 00:35:30
2016-10-11 @ 13:59:48 -- Board: AFNA, version: 2
2016-10-11 @ 13:59:48 -- Unique device ID received - 0x66dff484848667267251343

I'm able to connect fine to the latest BLHeliSuite:
![screen shot 2016-10-11 at 1 57 32 pm](https://cloud.githubusercontent.com/assets/2118422/19271215/84ebc32a-8fbb-11e6-9439-404fbe1b0371.png)

But this is what I get on the blheli-configurator:
![screen shot 2016-10-11 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/2118422/19271226/902f02ec-8fbb-11e6-9b80-e389803a7eb1.png)

Is there any way I can get more detailed debug information?

**Comment by DieHertz** [comment]
Could you have a look at the developer's console? There may be some messages.

**Comment by DieHertz** [comment]
You've checked out the repository from git and trying to run it? Have you executed the build command?
```npm run build```

It's not yet ready for public consumption, I'll add a readme on how to build it etcetera a bit later.

**Comment by sean-duffy** [comment]
Ah no I hadn't built it, didn't realise I had to do that. :)

I'm getting "ReferenceError: Unknown plugin "syntax-async-functions" specified in "/Users/SeanDuffy/Programming/projects/blheli-configurator/.babelrc" at 0" now though, but I'll give you a chance to get the readme together.

**Comment by DieHertz** [comment]
Sure. Thanks, I'll check what may be wrong with babel plugins, probably the `package.json` definitions.
IIRC, you should also run `npm install` prior to anything else, but I will surely add this to BUILD steps into the readme.
As well as a disclaimer :-)

**Comment by sean-duffy** [comment]
Excellent, that did the trick! Reads my setup fine now, great work on this.
