### ISSUE TITLE
16.67RC Not available in configurator

### ISSUE THREAD

**Issue by jollyrogeruk** [blheli-configurator/blheli-configurator#80]
I'm currently running Q-H 16.6 on spedix IS30A esc's and want to try D-Shot commands (anti-turtle etc).  I believe that I need version 16.67, but the latest version shown in configurator is 16.5.
I have checked that configurator is the latest version etc and have the same problem with Blhelisuite.
Can I manually download this hex from somewhere?

Thanks in advance

**Comment by DieHertz** [comment]
Delete the app and install it again
