### ISSUE TITLE
Esc loosing signal

### ISSUE THREAD

**Issue by Donkeyland74** [blheli-configurator/blheli-configurator#83]
Yesterday when I got to the flying field by quad would arm but only one ESC would spin. The day prior to quad flew fine without any crashes.    I got home and connected to computer because I am running race flight I flashed the board with Beta flight and went to the BL HeliI suite and 3 of the esc would not load.  I reflashed blheli and the esc showed up again.  I then reinstalled raceflight firmware and quad flies great.  Not sure what would cause the issue but if anyone has any ideas that would be great.  I gues I will be keeping my laptop in my bag in case this happens again.

**Comment by DieHertz** [comment]
You've reported your issue to a wrong repository, please proceed to either one:
https://github.com/4712/BLHeliSuite
https://github.com/bitdump/BLHeli
