### ISSUE TITLE
ESC desync

### ISSUE THREAD

**Issue by hpvok13** [blheli-configurator/blheli-configurator#84]
I'm flying the eachine wizard with stock, eachine blheli_s escs, and whenever I throttle up on the tx, I start to get desyncing. The motors will spool up as I increase throttle rapidly, but when I decrease throttle, two motors will stay at that rpm while the other two will fall back to min throttle. I do not get this issue when in the motors tab of betaflight, which makes me think it might be the fc or the pids, but I'm not sure. I'm not sure if this is caused by the escs or the fc, but I'm really confused and would appreciate any help. 
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1369233/Log.txt)

**Comment by DieHertz** [comment]
Hi!
Your issue sounds like a support requires for BLHeli, please report it to the following repository or to a corresponding RCGroups discussion thread.
https://github.com/bitdump/BLHeli
