### ISSUE TITLE
Blheli not recognize any esc

### ISSUE THREAD

**Issue by LordOkami** [blheli-configurator/blheli-configurator#86]
I'm trying to flash Racerstar Tattoo 30A BLheli_32 STM32F051 DShot1200 ESC and can't read any configuration from esc. All motors works well in betaflight configurator, I have tried with 3.0.1 betaflight version.
[blheli log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1425301/blheli.log.txt)

**Comment by richard-scott** [comment]
What FC do you use? F1 boards don't have passthrough capability anymore.

**Comment by DieHertz** [comment]
BLHeli32 is not supported.
