### ISSUE TITLE
Does Not Work with Lumenier ALPHA AIO Flight Controller

### ISSUE THREAD

**Issue by mlwellbaum** [blheli-configurator/blheli-configurator#87]
[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1435126/Log.txt)

Connects to FC but returns no information after reading setup

**Comment by richard-scott** [comment]
Are you using the suite from here: http://www.blheli32.com/download/

**Comment by mlwellbaum** [comment]
No. I’m using the Chrome Blheli Configurator.

Mike

**Comment by richard-scott** [comment]
The Chrome Blheli Configurator doesn't work with Blheli32 ESC's.

**Comment by DzikuVx** [comment]
@richard-scott it will probably never work with BLHeli32 and @DieHertz stated that multiple times.

@mlwellbaum this is rather not Configurator issue, but software that is running this flight controller

**Comment by mlwellbaum** [comment]
Good to know...thanks!

Mike

**Comment by yattiyada** [comment]
so will it EVER support Blheli_32?
