### ISSUE TITLE
racerstar 30A esc's connect but "read settings" stays blank

### ISSUE THREAD

**Issue by rogue-medic** [blheli-configurator/blheli-configurator#89]
as title, esc's wont allow read or alteration of settings.

log attached.......using the ESCs the same as from "https://www.banggood.com/Anniversary-Special-Edition-Racerstar-Tattoo-30A-BLheli_32-ST-2-4S-RaceSpec-ESC-DShot1200-p-1181811.html?rmmds=search&cur_warehouse=CN"

[Log.txt](https://github.com/blheli-configurator/blheli-configurator/files/1456742/Log.txt)

**Comment by DieHertz** [comment]
No blheli32

**Comment by ScottDunk** [comment]
Why did this get closed, i have the exact same issue

I need to reverse 2 motors and dont want to swap wires.  How do I get these ESC's to connectto BLHELI through Matek f405
