### ISSUE TITLE
Standalone configurator?

### ISSUE THREAD

**Issue by chaotixtech** [blheli-configurator/blheli-configurator#96]
With the move by Google to stop Chrome apps apart from on Chromebooks, Betaflight have released a standalone configurator for Windows, Osx and Linux. Is there any word on the same happening for Blheli? As a Mac user I am keen to be able to continue to fully set up my quads on my Macbook.

**Comment by YanikTheYak** [comment]
I believe this is in the works. 
I saw a pull request the other day, which looks like it will be doing this.
