### ISSUE TITLE
Calibrate ESCs like BLHeliSuite

### ISSUE THREAD

**Issue by josinaldobarbosa** [blheli-configurator/blheli-configurator#98]
Is it possible to put this functionality?

![](https://www.propwashed.com/wp-content/uploads/2016/08/up_throttle_1_sm.png)

**Comment by YanikTheYak** [comment]
Hi
You can do this in Betaflight can't you?
Just wondering why you'd need it in blheli as well?
Or is there something specific Betaflight won't do?

Regards
Ian
