### ISSUE TITLE
Strange firmware

### ISSUE THREAD

**Issue by rondofpv** [blheli-configurator/blheli-configurator#99]
Hi there, just flashed 16.7, it was ok for 1 second then it displays a strange name.  I'm unable to reflash it.  Help appreciated.
<img width="339" alt="screen shot 2017-12-14 at 10 38 08 pm" src="https://user-images.githubusercontent.com/30725525/33997654-0dff9fa4-e120-11e7-93ae-92ece9aa25de.png">

**Comment by DieHertz** [comment]
"ignore MCU and layout"

**Comment by rondofpv** [comment]
sorry i dont understand.. any idea how to reflash?

**Comment by DieHertz** [comment]
Check above-mentioned checkbox on firmware selection tab

**Comment by rondofpv** [comment]
ah i see. it worked. thanks so much for the swift reply.
